### ISSUE TITLE
Nosniff - Accessing theming admin interface

### ISSUE THREAD

**Issue by Dubidubiduu** [eneiluj/welcome#5]
2. Then when accessing theming admin I ran into `Die Ressource von "/index.php/apps/dashboard/" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).`. Had to fix via .htaccess commenting this lines to
```
#    Header onsuccess unset X-Content-Type-Options
#    Header always set X-Content-Type-Options "nosniff
```

But then my nextcloud is a little bit more insecure I guess?!

**Comment by eneiluj** [comment]
The welcome admin settings (placed in theming section) are not accessing anything placed in `/index.php/apps/dashboard/`. I don't know what happens to you.

Could you revert the changes you made in `.htaccess` and check if the error is gone after disabling the welcome app? If the error is still there, it has no relation with the welcome app :grin:.

**Comment by Dubidubiduu** [comment]
> 
> 
> The welcome admin settings (placed in theming section) are not accessing anything placed in `/index.php/apps/dashboard/`. I don't know what happens to you.
> 
> Could you revert the changes you made in `.htaccess` and check if the error is gone after disabling the welcome app? If the error is still there, it has no relation with the welcome app 😁.

Error just occurs when I activate the app.. But maybe it's interconnected with other apps? Custom Menu or so?!

**Comment by eneiluj** [comment]
I have an idea of what it could be caused by. The admin settings javascript file is somehow not accessible through the webserver so the request is redirected to the dashboard page and there you get the mime type problem.

@Dubidubiduu @Julianoe I think for you 2 both, there is something wrong with file permissions or something specific to your context.

I've done many many apps and this never happened. This particular app is very basic and works just fine in my 4 test servers.

I just published a release on the appstore. Let's hope installing this app from there will make it work for you. I'm interested in your feedback!

**Comment by Julianoe** [comment]
The reason, at least on my side, seems to be quite stupid. The github does not appear to have a js/ folder....
It seems you share the app and document it in the readme as if it was a plug and play app but if I clone the repository, I have to "webpack" it before to generate the js folder and files. Not sure my server has what it needs to generate it right now.

**Comment by Julianoe** [comment]
Hi again to you both!
Here is the solution then:

-  `git clone` the repository locally or on the server directly. I did it locally because my server was not configured for building apps
- enter the folder
- run `npm install && npm run build`
- send the welcome folder to `/cloud/custom_apps` on your app install
- change the permissions of the folder with `chown www-data:www-data welcome -R` (change group:user name depending on your system)
- make sure the _theming_ app is install and active
- set the welcome file in https://example.com/settings/admin/theming

**Comment by eneiluj** [comment]
@Julianoe Well you downloaded the source code. :grin: The installable app archive is the one named like that:
`welcome-x.x.x.tar.gz`. No need to build the app yourself. (plus you didn't build it correctly :grin:)

> I think the readme should at least mention the fact that this app needs theming app installed and active. Not all users use it by default.

I'll do it for sure.

**Comment by Julianoe** [comment]
rofl i did not see the releases associated with the repo haha 😂 I should get more sleep I guess.
Well at least it worked. I know I was lazy with building the app but it did the job : it gave me some js files ^^

 and now we maybe have a solution for @Dubidubiduu : just install the app using the archive here https://github.com/eneiluj/welcome/releases

**Comment by eneiluj** [comment]
> i did not see the releases associated with the repo

Another thing for me to include in the README!

@Dubidubiduu @Julianoe No more need to install the app with the release archive. It's in the appstore so it can be installed in Nextcloud app settings.

**Comment by Dubidubiduu** [comment]
Thanks
